spring.application.name=bellagestora

spring.datasource.url=jdbc:h2:mem:bellagestoradb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

api.security.token.secret=${JWT_SECRET:my-secret-key}

# Pede para o Hibernate recriar as tabelas toda vez que rodar o projeto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilita o painel visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
